spring:
  redis:
    host: 10.37.78.179
    port: 6379
  http:
    log-request-details: true
  datasource:
    url: jdbc:mysql://localhost:3306/ylyn
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
debug: false
logging:
  level:
    org:
      springframework:
        security: debug
server:
  port: 8081